services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chromium:latest
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=2
      - NODE_MAX_INSTANCES=2